# Generated by Django 4.2 on 2023-05-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_predict',
            field=models.BooleanField(default=False),
        ),
    ]
