# Generated by Django 4.2 on 2023-04-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='Email'),
        ),
    ]
